### PR TITLE
Failing polygon test

### PR DESCRIPTION
**Pull request by samraul**
Hi,

I am testing a few floorplans and I have found a case that causes an infinite loop in `_LAV`.
Please, see the attached test coordinates and how I detect the loop.

This is what the polygon looks like:
<kbd></kbd>

With all the coordinates from the test, _LAV enters in an infinite loop due to a circular dependency.

---

At first I thought it was due to vertices 0 and 1, since they may be collinear with respect to 16, and removing 0 makes the polygon work:

<kbd></kbd>

---

However, `Degenerate1` in the table below shows what I believe to be a wrong result, since vertex 3 does not have any connections, even though vertex 0 is removed. The other examples show different combinations of the vertices that also seem incorrect.

| Degenerate1 | Degenerate2 | Degenerate3 | Degenerate4 |
| ------------- | ------------- | ------------- | ------------- |
| <kbd></kbd>  | <kbd></kbd>  | <kbd></kbd>  | <kbd></kbd>

---

Am I missing something? I am surprised that this set of vertices has so many combinations that do not work properly.

### CODE REVIEW

**Comment by polarkernel** [comment]
Hi Raul

Thank you for your research and your suggestion to at least stop the infinite loop that occurs with this geometry. Finding a case that reproducibly causes an error is very valuable because it will help to improve the code.

I have not yet found the real cause of the problem, but some initial debug output suggests that vertex 0 at least starts the problem. At the beginning, the processes with and without vertex 0 do not differ. First, the split event 7 and the edge event 9 are processed in the top right corner of your floor plan (I will not explain the details of my plots, that would take us too far):

 

But when processing the split event 1, if vertex 1 is present, it is connected to the event (left plot), otherwise the event is connected to the corner vertex:

 

In the problem case, the regions are not separated at the split event (left plot) and the next processing step leads to the infinite loop. Without the additional vertex, the areas are separated, and the process continues without problems (right plot).

  

This gives me a defined state where I can start trying to find the bug. II will try to do this in the near future. In any case, we will merge your suggestion, possibly already with a bug fix, if possible.

Thank you
polarkernel

**Comment by samraul** [comment]
Thanks for the prompt reply @polarkernel.

I actually have another set of vertices that is problematic, so if you figure out the issue here, I will be eager to test the fix on that set as well.

---

For context, in this second set I noticed two issues:
* Some faces are missing (same issue than the degenerate cases in this PR).
* Some vertices returned in the extended vertex list are not part of any face
  * One of these vertices had massive coordinates, causing issues attempting to render the result.

These are the four unused vertices (not part of any face). Notice the coordinates of the third one. The other three are rendered in red in the image.
```
DISCARDING VERTEX: Vector((238.7581787109375, 1569.918212890625, 77.50455474853516))
DISCARDING VERTEX: Vector((213.03506469726562, 1569.95556640625, 92.35579681396484))
DISCARDING VERTEX: Vector((-6669949440.0, -6669948928.0, 3850897408.0))
DISCARDING VERTEX: Vector((169.29879760742188, 1772.9813232421875, 67.3052978515625))
```

| Top view  | 3D |
| ------------- | ------------- |
 <kbd></kbd> | <kbd></kbd> |

---
This is the code to detect those bogus vertices.

```
    used_vertex = [False] * len(VERTS)

    for face in faces:
        for edge in zip(face, face[1:] + face[:1]):
            p1, p2 = VERTS[edge[0]], VERTS[edge[1]]
            ax.plot([p1.x, p2.x], [p1.y, p2.y], [p1.z, p2.z], 'k')

            used_vertex[edge[0]] = True
            used_vertex[edge[1]] = True
    
    for i, v in enumerate(VERTS):
        if used_vertex[i]:
            ax.scatter(v.x, v.y, v.z, c='b')
        else:
            print(f"DISCARDING VERTEX: {v}")
            if v.z < 10000:
                ax.scatter(v.x, v.y, v.z, c='r')
```

**Comment by polarkernel** [comment]
@samraul: It will take some time, it's been several years since I last touched this code. I will have to relearn how that algorithm worked and what tricks I used to make it work. 

The floor plans of the 320,000 hipped roofs from the OpenStreetMap database that we tested at the time were all pre-processed to remove straight angle vertices. As far as I remember, we never had the case of infinite loops at this position. I am pretty sure that collinearity plays a role in this dataset, perhaps because of floating-point accuracy issues. One indication of this thought: when I added just 10 micrometers in the y-direction to your first vertex (0), the problem disappeared.

Floating-point accuracy problems came up very often in computational geometry problems that I had to solve. Unfortunately, I was not always able to find a solution. Sometimes it helped just to disturb the dataset by very small, noisy displacements.

**Comment by samraul** [comment]
> were all pre-processed to remove straight angle vertices

Ah, interesting. Thanks for the info. See below for tests related to `degenerate 1`. It does not seem to solve all cases.

> perhaps because of floating-point accuracy issues

Indeed, this can be an issue. I just did a quick test adding orders of magnitude to the coordinates, and the results are interesting:
* On the vanilla case (all coordinates), the circular dependency goes away, however the result is not 100% correct.
* Removing the straight angle (degenerate 1) does not produce correct results at all resolutions.

Test by multiplying and rounding coords:
```python
multiplier = 1
_COORDS = np.round(np.asarray(_COORDS) * multiplier, 2)
```

---

| 1x  | 10x | 100x | 1000x |
| ------------- | ------------- | ------------- | ------------- |
|  <kbd></kbd> | <kbd></kbd> | <kbd></kbd> | <kbd></kbd> |

---
`Degenerate 1`: Subset of 5 vertices with no straight angles. Indices `1, 2, 3, 4, 16` from original coords.

| 1x  | 10x | 100x | 1000x |
| ------------- | ------------- | ------------- | ------------- |
<kbd></kbd> | <kbd></kbd> | <kbd></kbd> | <kbd></kbd> |

It looks like the choke points are the issue, when two different regions need to be merged. I have no data to back this claim, just looking at the failing examples.

**Comment by polarkernel** [comment]
@samraul: I have a first result that explains the observation that a small shift of vertex 0 solves the problem. When processing a reflex vertex in the `next_event()` function, a test is performed to verify that the intersection point `B` is inside the triangle given by the opposite edge and the bisectors at their ends. Because the bisector vector at vertex 0, where we have nearly collinear edges, becomes zero length, this test passes for the opposite edge between the vertices 16 and 0, while it shouldn't.

A patch for now is to replace line [188](https://github.com/prochitecture/bpypolyskel/blob/5cdaea7d7649b082dcad7f40b3e0adcc4095535e/bpypolyskel/bpypolyskel.py#L188) from

```python
if not (xprev and xnext and xedge):
```
to
```python
parallel = edge.bisector_next.v.length == 0.
if not (xprev and xnext and xedge and not parallel):
```
Please test if this patch solves some of your problems. An additional note: In our tests, we used buildings from OpenStreetMap with their original dimensions in meters. The only normalization done in our code is to center the shape to its center of gravity. You are using very large buildings, and I don't know what effect this has on floating-point accuracy.

**Comment by samraul** [comment]
Interesting. My tests assumed that the polygon could come in any units, so these ones are in inches.

I have done quite a few ablation tests with several vertex combinations, and here are my findings:
* Your parallel fix alleviates the straight angle problem, but it does not fix all the issues.
* Coordinates in meters work **much** better than inches. In fact they seem to address all issues I have.
  * Floating point precision did not seem to have an impact, while downscaling does seem to.
  * I imagine this is due to some thresholds in the code that will not trigger with higher coordinate scales (39x for meter to inches).
* If you clean the straight angle, the loop issue goes away (we already knew this).

I have updated the PR to include a `clean_vertex` method that could be handy. Feel free to leave the PR open, merge some or all of it, or close it as _solved_.

In my case I will do both: **change coordinates to metric and clean vertices**. I will report back if I find more issues, but is seems that those two changes have a huge impact.

Thank you so much for the help, it seems we may have figured it out!

---

As for tests, here are some ablation results:


|                        | Vanilla in  | Vanilla metric | ParallelFix in  | ParallelFix metric |
| ------------- | :-------------: | :-------------: | :-------------: | :-------------: |
| **Unclean** Small | ❌ Infinite Loop Vanilla, ft | ❌Vanilla, m | ❌Parallel, ft | ❌Parallel, m |
| **Clean** Small | ✅Vanilla, ft, no0 |  ✅ Vanilla, m, no0 | ✅Parallel, ft, no0 |  ✅Parallel, m, no0
| **Unclean** Degenerate1 | ❌UnD1, Vanilla, ft | ❌UnD1, Vanilla, m |  ❌UnD1, Parallel, ft | ❌UnD1, Parallel, m |
| **Clean** Degenerate1 | ❌D1, Vanilla, ft |  ✅D1, Vanilla, m |  ✅ * no need |  ✅ * no need |
| Large | ❌2, Vanilla, ft |  ✅ 2, Vanilla, m | ❌ 2, Parallel, ft |  ✅ 2, Parallel, m | 

*not needed since the metric already works.

**Comment by polarkernel** [comment]
Until now, I was not aware of how sensitive _bpypolyskel_ is to scale, and that straight angle vertices may lead to errors. The library was developed to enable [Blosm for Blender](https://prochitecture.gumroad.com/l/blender-osm) to construct hipped roofs, its use as an independent library is just a by-product of this development. Since all known libraries that provide straight skeletons are not executable in Blender, we thought that developers there might find a use for _bpypolyskel_.

In all our tests, it was natural to use buildings, that were already cleaned for straight angle vertices, and dimensions in meters, as it was given in this addon. Your findings added valuable knowledge to the library and shed light on problems, that were unknown before. Thank you very much!

I will discuss with my partner, how to proceed with your PR.

**Comment by samraul** [comment]
Sounds good. Glad we could figure it out, and that the findings/code will be useful. 👍 
Thank you for your help looking into this with me.

**Comment by vvoovv** [comment]
Hi @samraul 

I committed your code that breaks an infinite cycle and the file _tests_special/test_loop.py_ manually.

We think that it's responsibility of a user to prepare data for the bpypolyskel library. Besides duplicated vertices, straight angles, a polygon can have a self-intersection, a degenerated part, etc. That's why we decided not to include the function `clean_verts`.

Thank you for your valuable contribution!

**Comment by samraul** [comment]
Sounds good. Even if the scaling issue remains somewhat hidden (some roofs will have holes at non-metric scale), at least it is a known issue now.

Thanks for the notification. Cheers!

**Pull request closed without merging**
